git add -f Documentation.pdf
git add -f git_add.sh
git add -f hash_list.json
git add -f data/BOMEX_enviro.txt
git add -f data/cloud_vel.txt
git add -f data/drop.data.new
git add -f data/en_ccn.dat
git add -f data/environment.txt
git add -f src/accu.f90
git add -f src/array.f90
git add -f src/assigd.f90
git add -f src/average.f90
git add -f src/const.f90
git add -f src/dgm.f90
git add -f src/domain.f90
git add -f src/drop_map.f90
git add -f src/eff_radius.f90
git add -f src/EMPM.f90
git add -f src/ew.f90
git add -f src/fcnkb.f90
git add -f src/fdtime.f90
git add -f src/fintrp.f90
git add -f src/index.f90
git add -f src/intpol.f90
git add -f src/Makefile
git add -f src/max_min.f90
git add -f src/mean_rms.f90
git add -f src/namelist
git add -f src/odeint.f90
git add -f src/prob.f90
git add -f src/psplint.f
git add -f src/psplint.f90
git add -f src/qt_prob.f90
git add -f src/radius_pdf.f90
git add -f src/rand1.f90
git add -f src/README.namelist
git add -f src/rkck.f90
git add -f src/rkqs.f90
git add -f src/rmax.f90
git add -f src/size_dis.f90
git add -f src/triplet.f90
